### ISSUE TITLE
Amatsukaのアプリケーションエラー

### ISSUE THREAD

**Issue by earlcorrin** [eiurur/Amatsuka#81]
先週辺りからamatsukaを開こうとするとApplication Errorと表示されるようになってしまいました。

**Comment by earlcorrin** [comment]
対応ありがとうございます。いつもお世話になっております。

**Comment by eiurur** [comment]
ご報告ありがとうございます。
ご指摘の障害はサーバの利用制限に引っかかっていたのが原因です。
以後、同じ問題が発生しないよう注意いたします。
